version: '3.8'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}shoppingapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
